### ISSUE TITLE
Inverse showing "wrong" values

### ISSUE THREAD

**Issue by henrique-borba** [phpsci/phpsci-ext#29]
@sanmai I need help on this one, when calling the inverse function (the one with lapack) I was expexting something like:

`[ 1.5, 2.0, ..]`

But It outputs:

`[1.5000000153849, 2.0000007284762... `

And so on. Is this actually correct?

Use matrix: `[[1 , 2], [3 , 4]]` for example

**Comment by henrique-borba** [comment]
You can also refer to Invert unit test:

```php
public function testInvertBasic()
{
        $expected = [
          [-2.0000002384186, 1.0000001192093],
          [1.5000001192093, -0.50000005960464]
        ];
        $a = ps::fromArray([[1, 2], [3, 4]]);
        $b = ps::inv($a);
        $this->assertEquals($expected, $b->toArray());
}
```

**Comment by sanmai** [comment]
It seems plausible.

**Comment by henrique-borba** [comment]
NumPy itself would output:
```php
[
          [-2.0, 1.0],
          [1.5, -0.5]
        
```
this worries me because NumPy is a very recognized and solid library.

**Comment by henrique-borba** [comment]
Notice that the values ​​have the same amount of decimals before a random number

**Comment by sanmai** [comment]
The numbers seems legit, because you cannot expect infinite precision for [an IEEE float](https://en.wikipedia.org/wiki/IEEE_754). See [machine epsilon](https://en.wikipedia.org/wiki/Machine_epsilon).

But what is wrong here is that *usually* PHP takes care of this issue, so you never see it in practice.

**Comment by henrique-borba** [comment]
Wow, nice. But how could values ​​be returned as they were supposed to be? (supposedly like the other libraries)

**Comment by sanmai** [comment]
I guess we're losing a lot of precision at some point because of a single-precision float somewhere in calculations. For double precision numbers PHP basically [ignores the tail of mantissa](http://php.net/manual/en/language.types.float.php), yet it is still there: https://3v4l.org/2ILQ7

**Comment by sanmai** [comment]
Can we switch to use `double` instead of `float` here? IIRC `float` is a single precision.

**Comment by henrique-borba** [comment]
It would be easy to change to double, I will just change the mallocs of the carray and the structure of the CArray, I will do this test now.

A detail that has nothing to do with this issue, but I think we have to take it seriously: The advantage of putting CArray in a single value with a shape property is that in case of N extra dimensions (3D, 4D...), we could broadcast like NumPy, so example : a 3D matrix would be N x 2D Matrices.

**Comment by henrique-borba** [comment]
I will lose some speed I guess.

**Comment by henrique-borba** [comment]
The same thing happens but in opposite way (number get smaller):
```php
1) PHPSci\Tests\LinearAlgebra\InvertTest::testInvertBasic
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Array (
-        0 => -2.0000002384186
-        1 => 1.0000001192093
+        0 => -1.9999999999999996
+        1 => 0.9999999999999998
     )
     1 => Array (
-        0 => 1.5000001192093
-        1 => -0.50000005960464
+        0 => 1.4999999999999998
+        1 => -0.4999999999999999
     )
 )
```

**Comment by sanmai** [comment]
Are you using `LAPACKE_dgetrf` and `LAPACKE_dgetri`? Notice `d` there.

**Comment by henrique-borba** [comment]
```php
$a = ps::fromArray([[1, 2], [3, 4]]);
$b = ps::inv($a);
echo $b;
```
outputs:
```php
[
  [ -2.000000  1.000000 ]
  [ 1.500000  -0.500000 ]
]
```
so is something with PHP

**Comment by henrique-borba** [comment]
Yes, I tested with `dgetrf`and `dgetri` after change to `* double` but problem persisted.

**Comment by henrique-borba** [comment]
I guess we found the problem:

```C
void carray_to_array(CArray carray, zval * rtn_array, int m, int n)
{
    int rows, cols;
    zval inner;
    array_init(rtn_array);
    if(n > 0) {
        for( rows = 0; rows < m; rows++ ) {
            array_init(&inner);
            for( cols = 0; cols < n; cols++ ) {
                add_next_index_double(&inner, (float)carray.array2d[(cols * m) + rows]);
            }
            add_next_index_zval(rtn_array, &inner);
        }
    }
    if(n == 0) {
        for( rows = 0; rows < m; rows++ ) {
            add_next_index_double(rtn_array, (float)carray.array1d[rows]);
        }
    }
}
```

**Comment by sanmai** [comment]
Yes, I saw that in other comment right after asking. So, do you see if there any floats left?  E.g. just a single cast to a single-precision float somewhere can ruin everything.

What kind of precision we can expect from `LAPACKE_dgetrf`? It could be decisively loosing precision so we have to round  numbers.

**Comment by sanmai** [comment]
`(float)carray.array2d` seems like it

**Comment by sanmai** [comment]
It seems like NumPy use a double precision numbers by default. And they say [most architectures can process double precision as fast as single precision floats](https://stackoverflow.com/a/42486504/93540).

**Comment by henrique-borba** [comment]
Same think after get rid of all floats:
```php
 Array (
     0 => Array (
-        0 => -2.0000002384186
-        1 => 1.0000001192093
+        0 => -1.9999999999999996
+        1 => 0.9999999999999998
     )
     1 => Array (
-        0 => 1.5000001192093
-        1 => -0.50000005960464
+        0 => 1.4999999999999998
+        1 => -0.4999999999999999
     )
 )
```
With echo stays:
```C
[
  [ -2.000000  1.000000 ]
  [ 1.500000  -0.500000 ]
]
```

**Comment by henrique-borba** [comment]
Perhaps the default setting of php `precision` is influencing this.

**Comment by henrique-borba** [comment]
```php
<?php
ini_set('precision', 6);
require_once "vendor/autoload.php";

use PHPSci\PHPSci as ps;

$a = 1000;
$step = 100;



$a = ps::fromArray([[1, 2], [3, 4]]);
$b = ps::inv($a);
print_r($b->toArray());
```
outputs:
```php
Array
(
    [0] => Array
        (
            [0] => -2
            [1] => 1
        )

    [1] => Array
        (
            [0] => 1.5
            [1] => -0.5
        )

)
```
I almost sure `precision` of PHP double is affecting this.

**Comment by sanmai** [comment]
What does `git grep float` show you?

**Comment by henrique-borba** [comment]
Thanks man! THAT'S IT. I feel like an idiot now, I was forcing the float in the PHP library. 
I tested it exclusively with CArray. I was so used to testing using the library that I forgot to test exclusively with the extension.
```
docs/array_initializers.md:public static function linspace(float $start, float $st
op, int $num);
docs/array_initializers.md:public static function logspace(float $start, float $st
op, int $num, float $base);
src/PHPSci/Kernel/PropertiesProcessor/took.php:     * @return float
src/PHPSci/Kernel/Ranges/Rangeable.php:     * @param float $stop  End of interval.
 The interval does not include
src/PHPSci/Kernel/Ranges/Rangeable.php:     *                     integer and floa
ting point round-off affects the length
src/PHPSci/Kernel/Ranges/Rangeable.php:     * @param float $start Start of interva
l. The interval includes this
src/PHPSci/Kernel/Ranges/Rangeable.php:     * @param float $step  Spacing between
values. For any output out, this
src/PHPSci/Kernel/Ranges/Rangeable.php:        float $stop,
src/PHPSci/Kernel/Ranges/Rangeable.php:        float $start = 0.,
src/PHPSci/Kernel/Ranges/Rangeable.php:        float $step = 1.
src/PHPSci/Kernel/Ranges/Rangeable.php:     * @param float $stop  The end value of
 the sequence.
src/PHPSci/Kernel/Ranges/Rangeable.php:     * @param float $start The starting val
ue of the sequence.
src/PHPSci/Kernel/Ranges/Rangeable.php:     * @param float $num   Number of sample
s to generate. Default is 50.
src/PHPSci/Kernel/Ranges/Rangeable.php:        float $start,
src/PHPSci/Kernel/Ranges/Rangeable.php:        float $stop,
src/PHPSci/Kernel/Ranges/Rangeable.php:        float $num = 50
is the starting value of the sequence.
s the final value of the sequence
e log space.
src/PHPSci/Kernel/Ranges/Rangeable.php:        float $start,
src/PHPSci/Kernel/Ranges/Rangeable.php:        float $stop,
src/PHPSci/Kernel/Ranges/Rangeable.php:        float $base = 10
src/PHPSci/Kernel/Transform/Transformable.php:     * @param  float $input
ble(float $input): CArrayWrapper
t($input)) {
```
Well I will then update and send the new standard with doubles.

**Comment by henrique-borba** [comment]
```php
$a = CArray::fromArray([[1, 2], [3, 4]]);
$b = CArray::inv($a);
print_r(CArray::toArray($b));
```
```php
Array
(
    [0] => Array
        (
            [0] => -2
            [1] => 1
        )

    [1] => Array
        (
            [0] => 1.5
            [1] => -0.5
        )

)
```
Like a charm.
