### ISSUE TITLE
config-m4 for LAPACKE won't work on Fedora 27

### ISSUE THREAD

**Issue by henrique-borba** [phpsci/phpsci-ext#30]
Using Fedora 27 I could only make it work with:
```m4
PHP_CHECK_LIBRARY(lapack,LAPACKE_sgetrf,
[
  PHP_ADD_LIBRARY(lapack)
],[
  AC_MSG_ERROR([wrong lapacke version or library not found])
],[
  -llapack
])
```
Is there a way to use both `-llapack` or `-llapacke` and only throw `AC_MSG_ERROR` if both failed?

I'll check if my environment is problematic.

**Comment by sanmai** [comment]
How about this?
```
PHP_CHECK_LIBRARY(lapack,LAPACKE_sgetrf,
[
  PHP_ADD_LIBRARY(lapack)
],[
  PHP_CHECK_LIBRARY(lapacke,LAPACKE_sgetrf,
  [
    PHP_ADD_LIBRARY(lapacke)
  ],[
    AC_MSG_ERROR([wrong lapacke version or library not found])
  ],[
    -llapacke
])
],[
  -llapack
])
```

**Comment by henrique-borba** [comment]
I'm finalizing some implementations and I'm going back to this issue. Thanks @sanmai 

(I think this will do)

PS: Big day, I commited a lot of new methods: `flatten`, `atleast_1d`, `atleast_2d`, `ones`, `zeros_like`, `ones_like`, `full`, `full_like`, `exp`, `log`, `eye`, `log10`, `log2`, `log1p`, `subtract`, `tan`, `sin`, `cos`, `arctan`, `arcsin`, `arccos`, `sinh`, `cosh`, `tanh` and `svd`. I needed to add some new ones because they were important and easy to implement. The SVD with LAPACK was a great success, correctly returning the three expected arrays (singular, left and right).

**Comment by sanmai** [comment]
@henrique-borba I'll take a look if there's an issue, for sure, but please give me some time.

**Comment by henrique-borba** [comment]
Hi @sanmai

Sorry about the delay, I had to finish some projects here in Brazil and lately I got breakbone fever (dengue fever), I was really fc** up.

Now I'm back and we can finally release =)

**Comment by henrique-borba** [comment]
@sanmai. Just updated the project. While porting SKLearn basic algorithms to PHP using CArrays I came across a lot of methods that our extension wasn't covering for the first release. I needed to implement them and most of them was implemented. We are talking at least of 20 new methods and properties.

After fixing some problems your __destruct implementation was implemented back. It's working really good and valgrind shows 0 memleaks.

I moved PHPSci project to an SKLearn/Keras alternative for PHP. It has a Plot library for CArrays and AI algorithms to give CArrays utility. I ported SKLearn Gaussian Naive Bayes algorithm to our library and it worked really good (the code looks the same!). It generates the exactly same results as SKLearn and works 12 times faster them the PHP-ML implementation.

One important method we should care of is "CArray::var", it calls many CArray methods internaly and most of them are not specialized. I'm sure we can improve it a lot more, the "var" static method takes 50% of the trainning time.

**Comment by henrique-borba** [comment]
@sanmai. Just updated the project. While porting SKLearn basic algorithms to PHP using CArrays I came across a lot of methods that our extension wasn't covering for the first release. I needed to implement them and most of them was implemented. We are talking at least of 20 new methods and properties.

After fixing some problems your __destruct implementation was implemented back. It's working really good and valgrind shows 0 memleaks.

I moved PHPSci project to an SKLearn/Keras alternative for PHP. It has a Plot library for CArrays and AI algorithms to give CArrays utility. I ported SKLearn Gaussian Naive Bayes algorithm to our library and it worked really good (the code looks the same!). It generates the exactly same results as SKLearn and works 12 times faster them the PHP-ML implementation.

One important method we should care of is "CArray::var", it calls many CArray methods internaly and most of them are not specialized. I'm sure we can improve it a lot more, the "var" static method takes 50% of the trainning time.

**Comment by henrique-borba** [comment]
Our naive bayes code:
https://github.com/phpsci/phpsci/blob/master/src/PHPSci/NaiveBayes/GaussianNB.php

Youi can take a look at SKLearn GaussianNB class to see how close they are.

(I'm not intending to steal SKLearn code, I'm just porting it because I don't understand as much as they do of Machine Learning, and I don't think we need to build "the wheel" again, Scikit Learn is a mature AI library and I think we should base on it. I will always include @see for SKLearn documentation in our code when necessary)
