### ISSUE TITLE
N-dimensional support and CArray struct fixes

### ISSUE THREAD

**Issue by henrique-borba** [phpsci/phpsci-ext#47]
@sanmai After some heavy study into Numpy source code and some threads on Reddit I finally came with a solution for our ND CArray. It was so obvious, basically we should migrate array0d, array1d...etc, into a void * data_buffer and add a int * stride and int * shape to our struct. This allow us to maintain a contiguous C array with N dimensional support using shape and stride to access the N dimensions, without the need of linked lists. So considering an 3d matrix of shape [2, 3, 4] we can access the element [0,1,2] with a[(0 * 24) + (1 * 12) + (2 * 4)]. It's an heavy implementation but it's the right way to go. (4 bytes considering ints only, in our case would be double bytes). Using void * would allow us to allocate any type of data (scalars, ints and doubles). My only concern right now except implementation is how CBlas would handle the void * data buffer, it actually expect double * matrix.

**Comment by henrique-borba** [comment]
`
/*
 * Helper: dispatch to appropriate cblas_?gemm for typenum.
 */
static void
gemm(int typenum, enum CBLAS_ORDER order,
     enum CBLAS_TRANSPOSE transA, enum CBLAS_TRANSPOSE transB,
     int m, int n, int k,
     PyArrayObject *A, int lda, PyArrayObject *B, int ldb, PyArrayObject *R)
{
    const void *Adata = PyArray_DATA(A), *Bdata = PyArray_DATA(B);
    void *Rdata = PyArray_DATA(R);
    int ldc = PyArray_DIM(R, 1) > 1 ? PyArray_DIM(R, 1) : 1;

    switch (typenum) {
        case NPY_DOUBLE:
            cblas_dgemm(order, transA, transB, m, n, k, 1.,
                        Adata, lda, Bdata, ldb, 0., Rdata, ldc);
            break;
        case NPY_FLOAT:
            cblas_sgemm(order, transA, transB, m, n, k, 1.f,
                        Adata, lda, Bdata, ldb, 0.f, Rdata, ldc);
            break;
        case NPY_CDOUBLE:
            cblas_zgemm(order, transA, transB, m, n, k, oneD,
                        Adata, lda, Bdata, ldb, zeroD, Rdata, ldc);
            break;
        case NPY_CFLOAT:
            cblas_cgemm(order, transA, transB, m, n, k, oneF,
                        Adata, lda, Bdata, ldb, zeroF, Rdata, ldc);
            break;
    }
}
`

**Comment by henrique-borba** [comment]
That `PyObject * base` is important too, if we slice our CArray the way it is implemented, it will create another CArray and so on.

```
PyObject *PyArrayObject.base¶
This member is used to hold a pointer to another Python object that is related to this array. There are two use cases: 1) If this array does not own its own memory, then base points to the Python object that owns it (perhaps another array object), 2) If this array has the (deprecated) NPY_ARRAY_UPDATEIFCOPY or :c:data:NPY_ARRAY_WRITEBACKIFCOPY`: flag set, then this array is a working copy of a “misbehaved” array. When PyArray_ResolveWritebackIfCopy is called, the array pointed to by base will be updated with the contents of this array.
```

**Comment by sanmai** [comment]
That'll be very beneficial for anything sufficiently large. And this can be done in the internals only: no need to go into hurdles integrating this functionality into the larger library, at least for time being. Say, you can store the array as is, and dimensions aside, only changing the dimensions when requested, and only changing the array when needed. As I understand, [that's what NumPy does](https://docs.scipy.org/doc/numpy-1.13.0/reference/c-api.array.html#c.PyArray_Newshape).

So it'll be another level of abstraction deeper.

**Comment by henrique-borba** [comment]
I had commited some codes for this ND implementation. 

https://github.com/phpsci/phpsci-ext/tree/1.0-dev

**CArray Structs**
```C
/**
 * CArray
 */
typedef struct CArray CArray;
struct CArray {
    int * strides;      // Strides vector
    int * dimensions;   // Dimensions size vector (Shape)
    int ndim;           // Number of Dimensions
    char * data;        // Data Buffer
    CArray * base;      // Used when sharing memory from other CArray (slices, etc)
    int flags;          // Describes CArray memory approach (Memory related flags)
    CArrayDescriptor descriptor;    // CArray data descriptor
};
```
**CArray Descriptor**
Describes the data within CArray
```C
/**
 * CArray Descriptor
 */
typedef struct CArrayDescriptor {
    char type;          // b = boolean, d = double, i = signer integer, u = unsigned integer, f = floating point, c = char
    int flags;          // Data related flags
    int type_num;       // 0 = boolean, 1 = double, 2 = signed integer, 3 = unsigned integer, 4 = floating point, 5 = char
    int elsize;         // Datatype size
    int numElements;    // Number of elements
} CArrayDescriptor;
```

I implemented the first allocations, strides and dimensions mechanism, the results sor far looks like:
_Using CArray_Dump within CArray_INIT code_
```PHP
$a = new CArray([1, 2, 3, 4, 5]);
```
```
CArray.dims                     [ 5 ]
CArray.strides                  [ 4 ]
CArray.ndim                     1
CArray.descriptor.elsize        4
CArray.descriptor.numElements   5
CArray.descriptor.type          i
CArray.descriptor.type_num      2
CArray.descriptor.elsize        4
```
```PHP
$a = new CArray([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]);
```
```
CArray.dims                     [ 2 5 ]
CArray.strides                  [ 20 4 ]
CArray.ndim                     2
CArray.descriptor.elsize        4
CArray.descriptor.numElements   10
CArray.descriptor.type          i
CArray.descriptor.type_num      2
CArray.descriptor.elsize        4
```

```PHP
<?php
$a = new CArray([
    [
        [
            [
                [1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [1, 2, 3, 4, 5],[6, 7, 8, 9, 10]
            ],
            [
                [1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [1, 2, 3, 4, 5],[6, 7, 8, 9, 10]
            ],
            [
                [1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [1, 2, 3, 4, 5],[6, 7, 8, 9, 10]
            ],    
        ]
    ],
    [
        [
            [
                [1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [1, 2, 3, 4, 5],[6, 7, 8, 9, 10]
            ],
            [
                [1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [1, 2, 3, 4, 5],[6, 7, 8, 9, 10]
            ],
            [
                [1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [1, 2, 3, 4, 5],[6, 7, 8, 9, 10]
            ],    
        ]
    ],
    [
        [
            [
                [1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [1, 2, 3, 4, 5],[6, 7, 8, 9, 10]
            ],
            [
                [1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [1, 2, 3, 4, 5],[6, 7, 8, 9, 10]
            ],
            [
                [1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [1, 2, 3, 4, 5],[6, 7, 8, 9, 10]
            ],    
        ]
    ]
]);
```
```
CArray.dims                     [ 3 1 3 4 5 ]
CArray.strides                  [ 240 240 80 20 4 ]
CArray.ndim                     5
CArray.descriptor.elsize        4
CArray.descriptor.numElements   180
CArray.descriptor.type          i
CArray.descriptor.type_num      2
CArray.descriptor.elsize        4
```

**Comment by henrique-borba** [comment]
@sanmai It works so much better now! I have reused the NumPy code structures and implemented their iterators by merging with our buffer model and removing unnecessary structures (NumPy Arrays are Python objects by nature so I had to remove many snippets and arguments for Python objects).

Here is an example below containing a reshape and a sum of an N-dimensional array with the new implementation. If you want to test, just use the branch 1.0-dev. I also did a performance comparison and the sum method in our library works faster than in NumPy (possibly because of code cleanup and snippets for Python). Anyway the difference is minimal (3 microseconds)

**Reshape**
```PHP
$b = new CArray([[[[2, 3], [4, 5]], [[6, 7], [8, 9]]]]);
echo $b->print();
$c = $b->reshape([8]);
echo $c->print();
$d = $b->reshape([2, 4]);
echo $d->print();
```
```
[[[[ 2  3 ][ 4  5 ]][[ 6  7 ][ 8  9 ]]]]
[ 2  3  4  5  6  7  8  9 ]
[[ 2  3  4  5 ][ 6  7  8  9 ]]
```

**SUM WITH AXIS: CArray::sum(CArray $array, int $axis)**
```PHP
$b = new CArray([[[[2, 3], [4, 5]], [[6, 7], [8, 9]]]]);
echo CArray::sum($b)->print();           // No axis
echo CArray::sum($b, 0)->print();       // Axis = 0
echo CArray::sum($b, 1)->print();       // Axis = 1
echo CArray::sum($b, 2)->print();       // Axis = 2
```

```PHP
44 // No Axis
[[[ 2  3 ][ 4  5 ]][[ 6  7 ][ 8  9 ]]] // Axis = 0
[[[ 8  10 ][ 12  14 ]]] // Axis = 1
[[[ 6  8 ][ 14  16 ]]] // Axis = 2
```

**NEW: CArray Views/Copy**
The CArrays, like numpy, work with Views, so when we use Reshape, the result array is an CArray View, using the same data buffer and increasing the original object reference. Here is an example where you can check the refcount of the original object after the reshape.

```PHP
$b = new CArray([[[[2, 3], [4, 5]], [[6, 7], [8, 9]]]]);

// Dump before reshape
$b->dump();
$c = $b->reshape([8]);
// Dump after reshape
$b->dump();
```

```
// Before
CArray.dims                     [ 1 2 2 2 ]
CArray.strides                  [ 32 16 8 4 ]
CArray.ndim                     4
CArray.refcount                 0
CArray.descriptor.elsize        4
CArray.descriptor.numElements   8
CArray.descriptor.type          i
CArray.descriptor.type_num      2

// After
CArray.dims                     [ 1 2 2 2 ]
CArray.strides                  [ 32 16 8 4 ]
CArray.ndim                     4
CArray.refcount                 1                   // REFCOUNT INCREASED
CArray.descriptor.elsize        4
CArray.descriptor.numElements   8
CArray.descriptor.type          i
CArray.descriptor.type_num      2
```
When GC calls the __destruct method of `$b`, it will free the original CArray but it won't free the data buffer if it's refcount is bigger them one.

**Comment by henrique-borba** [comment]
New ND implementation is working perfectly do I will close this issue.
