### ISSUE TITLE
Destroy method not defined

### ISSUE THREAD

**Issue by jdvallejor** [phpsci/phpsci-ext#48]
Hello,

When I call the mehod CArray::destroy($array) this is not defined. By the way, thanks for the work you have done!!

**Comment by henrique-borba** [comment]
Hi @jdvallejor, thank you!

The documentation is actually outdated, CArrays now uses __destruct for Garbage Collection, so they are now freed automatically as soon PHP GC enters on action. If you want to cleanup manually you can always use "unset" to call the destructor:

````php
unset($array);
```

I created issue #49 with the information you provided.
